import { config, library } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { faGithub, faYoutube } from '@fortawesome/free-brands-svg-icons';
import {
  faAngry,
  faBookmark as faRegularBookmark,
  faCheckCircle as faRegularCheckCircle,
  faCheckSquare as faRegularCheckSquare,
  faComment as faRegularComment,
  faCommentAlt as faRegularCommentAlt,
  faCommenting as faRegularCommenting,
  faDizzy,
  faEdit as faRegularEdit,
  faEnvelope as faRegularEnvelope,
  faEye as faRegularEye,
  faEyeSlash as faRegularEyeSlash,
  faFlushed,
  faFolderBlank as faRegularFolderBlank,
  faFrown,
  faFrownOpen,
  faGrimace,
  faGrin,
  faGrinAlt,
  faGrinBeam,
  faGrinBeamSweat,
  faGrinHearts,
  faGrinSquint,
  faGrinSquintTears,
  faGrinStars,
  faGrinTears,
  faGrinTongue,
  faGrinTongueSquint,
  faGrinTongueWink,
  faGrinWink,
  faImage as faRegularImage,
  faKiss,
  faKissBeam,
  faKissWinkHeart,
  faLaugh,
  faLaughBeam,
  faLaughSquint,
  faLaughWink,
  faListAlt as faRegularListAlt,
  faMeh,
  faMehBlank,
  faMehRollingEyes,
  faSadCry,
  faSadTear,
  faSmileBeam,
  faSmileWink,
  faSquare as faRegularSquare,
  faStar as faRegularStar,
  faStarHalfAlt as faRegularStarHalfAlt,
  faSurprise,
  faTired,
  faUser as faRegularUser,
  faXmarkCircle as faRegularXmarkCircle,
} from '@fortawesome/free-regular-svg-icons';
import {
  faAdd,
  faArrowRight,
  faArrowUp,
  faArrowsToDot,
  faBold,
  faBookmark,
  faBullhorn,
  faChain,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleNotch,
  faCog,
  faCode,
  faComment,
  faCommentAlt,
  faCommenting,
  faDesktopAlt,
  faEdit,
  faEllipsisH,
  faEnvelope,
  faExclamationCircle,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFileEdit,
  faFire,
  faFolderBlank,
  faHomeLgAlt,
  faImage,
  faInfo,
  faInfoCircle,
  faItalic,
  faListAlt,
  faListSquares,
  faLock,
  faM,
  faMailForward,
  faMailReply,
  faNavicon,
  faQuoteRightAlt,
  faRotateForward,
  faSave,
  faSearch,
  faSearchMinus,
  faShieldAlt,
  faShieldBlank,
  faSignOutAlt,
  faSquare,
  faStar,
  faStarHalfAlt,
  faStepBackward,
  faStepForward,
  faStream,
  faStrikethrough,
  faSubtract,
  faSync,
  faT,
  faThList,
  faThumbTack,
  faTimes,
  faTrash,
  faUnderline,
  faUser,
  faWarning,
} from '@fortawesome/free-solid-svg-icons';

// Prevent Font Awesome from injecting CSS at runtime. We import the stylesheet explicitly.
config.autoAddCss = false;

library.add(
  faGithub,
  faYoutube,
  faAngry,
  faRegularBookmark,
  faRegularCheckCircle,
  faRegularCheckSquare,
  faRegularComment,
  faRegularCommentAlt,
  faRegularCommenting,
  faDizzy,
  faRegularEdit,
  faRegularEnvelope,
  faRegularEye,
  faRegularEyeSlash,
  faFlushed,
  faRegularFolderBlank,
  faFrown,
  faFrownOpen,
  faGrimace,
  faGrin,
  faGrinAlt,
  faGrinBeam,
  faGrinBeamSweat,
  faGrinHearts,
  faGrinSquint,
  faGrinSquintTears,
  faGrinStars,
  faGrinTears,
  faGrinTongue,
  faGrinTongueSquint,
  faGrinTongueWink,
  faGrinWink,
  faRegularImage,
  faKiss,
  faKissBeam,
  faKissWinkHeart,
  faLaugh,
  faLaughBeam,
  faLaughSquint,
  faLaughWink,
  faRegularListAlt,
  faMeh,
  faMehBlank,
  faMehRollingEyes,
  faSadCry,
  faSadTear,
  faSmileBeam,
  faSmileWink,
  faRegularSquare,
  faRegularStar,
  faRegularStarHalfAlt,
  faSurprise,
  faTired,
  faRegularUser,
  faRegularXmarkCircle,
  faAdd,
  faArrowRight,
  faArrowUp,
  faArrowsToDot,
  faBold,
  faBookmark,
  faBullhorn,
  faChain,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleNotch,
  faCog,
  faCode,
  faComment,
  faCommentAlt,
  faCommenting,
  faDesktopAlt,
  faEdit,
  faEllipsisH,
  faEnvelope,
  faExclamationCircle,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFileEdit,
  faFire,
  faFolderBlank,
  faHomeLgAlt,
  faImage,
  faInfo,
  faInfoCircle,
  faItalic,
  faListAlt,
  faListSquares,
  faLock,
  faM,
  faMailForward,
  faMailReply,
  faNavicon,
  faQuoteRightAlt,
  faRotateForward,
  faSave,
  faSearch,
  faSearchMinus,
  faShieldAlt,
  faShieldBlank,
  faSignOutAlt,
  faSquare,
  faStar,
  faStarHalfAlt,
  faStepBackward,
  faStepForward,
  faStream,
  faStrikethrough,
  faSubtract,
  faSync,
  faT,
  faThList,
  faThumbTack,
  faTimes,
  faTrash,
  faUnderline,
  faUser,
  faWarning,
);
