name: pull-request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  lint:
    uses: .github/workflows/npm_lint.yml

  test:
    uses: .github/workflows/npm_test-coverage.yml
