name: pull-request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  lint:
    uses: potber/.github/.github/workflows/npm_lint.yml@v1

  test:
    uses: potber/.github/.github/workflows/npm_test-coverage.yml@v1
