on:
  workflow_call:
    inputs:
      dockerfile:
        description: "The dockerfile path relative to the root folder. Defaults to 'Dockerfile'."
        default: Dockerfile
        type: string
      latest:
        description: "Whether the image should also be tagged as the latest image. Can be either 'auto', 'true' or 'false'. Defaults to 'auto'."
        default: "auto"
        type: string

jobs:
  get_metadata:
    uses: ./.github/workflows/get_metadata.yml
    with:
      latest: ${{ inputs.latest }}

  build_and_push_image:
    needs:
      - get_metadata
    uses: ./.github/workflows/build_and_push_image.yml
    with:
      image_name: ${{ needs.get_metadata.outputs.image_name }}
      image_names: ${{ needs.get_metadata.outputs.image_names }}
      image_labels: ${{ needs.get_metadata.outputs.image_labels }}
      dockerfile: ${{ inputs.dockerfile }}
