name: staging

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: potber/.github/workflows/npm_lint.yml@v1

  test:
    uses: potber/.github/workflows/npm_test-coverage.yml@v1

  release_image:
    needs:
    - lint
    - test
    permissions:
      contents: read
      packages: write
    uses: potber/.github/workflows/release_image.yml@v1
